apiVersion: v1
kind: Service
metadata:
  name: buslfurs-web
  labels:
    app.kubernetes.io/name: buslfurs-web
spec:
  selector:
    app.kubernetes.io/name: buslfurs-web
  ports:
    - name: http
      port: 80
      targetPort: http
