apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: production
images:
- name: buslfurs-web
  newName: ghcr.io/phill93/bruslfurs-web
  newTag: c599de2c6d66-48
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: brusler-furs.de
  target:
    kind: Ingress
    name: buslfurs-web
