apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
labels:
  - pairs:
      app.kubernetes.io/instance: production
    includeSelectors: true
images:
  - name: buslfurs-web
    newName: ghcr.io/OWNER/REPOSITORY
    newTag: initial
patches:
  - target:
      kind: Ingress
      name: buslfurs-web
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: brusler-furs.de
